//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol EJScreenCaptureDelegate;

@interface EJFrameCapture : NSObject
{
    id <EJScreenCaptureDelegate> delegate;
    unsigned int frameSize;
    char *frameBuffer;
}

+ (id)sharedInstance;
@property(nonatomic) __weak id <EJScreenCaptureDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (_Bool)isScreenCaptureStart;
- (void)capture:(unsigned int)arg1 height:(unsigned int)arg2;
- (void)captureIfNeeded:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)init;

@end

