//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol EJScreenCaptureDelegate <NSObject>
- (void)onScreenCapture:(void *)arg1 size:(unsigned long long)arg2 width:(unsigned long long)arg3 height:(unsigned long long)arg4 bitsPerComponent:(unsigned long long)arg5 bytesPerRow:(unsigned long long)arg6 bitmapInfo:(unsigned int)arg7;
- (_Bool)isScreenCaptureStart;
@end

