//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "MMUIHalfScreenViewDismissInteractiveTransitionDelegate-Protocol.h"
#import "MMUIHalfScreenViewPresentationAnimateTransitionDelegate-Protocol.h"

@class MMUIButton, MMUIHalfScreenViewDismissInteractiveTransition, MMUIHalfScreenViewPresentationAnimateTransition, MMUIView, NSString, UIPanGestureRecognizer, UIScreenEdgePanGestureRecognizer, UIScrollView, UIView;
@protocol MMUIHalfScreenViewControllerDelegate;

@interface MMUIHalfScreenViewController : MMUIViewController <MMUIHalfScreenViewDismissInteractiveTransitionDelegate, MMUIHalfScreenViewPresentationAnimateTransitionDelegate>
{
    MMUIView *m_maskView;
    double m_maxHalfScreenHeight;
    _Bool _isHideSetupGradientEffect;
    _Bool _isHideBackgroupMask;
    double _halfScreenHeight;
    long long _halfScreenViewControllerModel;
    id <MMUIHalfScreenViewControllerDelegate> _delegate;
    UIView *_detailView;
    MMUIButton *_closeButton;
    MMUIView *_topView;
    MMUIView *_contentView;
    MMUIButton *_backgroundButton;
    UIPanGestureRecognizer *_panGesture;
    UIScrollView *_detaiInSideScrollView;
    UIScreenEdgePanGestureRecognizer *_popBackInteractivePopGesture;
    MMUIHalfScreenViewDismissInteractiveTransition *_dimissInteractiveTransition;
    MMUIHalfScreenViewPresentationAnimateTransition *_resentationAnimate;
    double _dragDownCloseFriendsScrollViewDistance;
    double _dragUpToTopScrollViewDistance;
}

@property(nonatomic) double dragUpToTopScrollViewDistance; // @synthesize dragUpToTopScrollViewDistance=_dragUpToTopScrollViewDistance;
@property(nonatomic) double dragDownCloseFriendsScrollViewDistance; // @synthesize dragDownCloseFriendsScrollViewDistance=_dragDownCloseFriendsScrollViewDistance;
@property(retain, nonatomic) MMUIHalfScreenViewPresentationAnimateTransition *resentationAnimate; // @synthesize resentationAnimate=_resentationAnimate;
@property(retain, nonatomic) MMUIHalfScreenViewDismissInteractiveTransition *dimissInteractiveTransition; // @synthesize dimissInteractiveTransition=_dimissInteractiveTransition;
@property(retain, nonatomic) UIScreenEdgePanGestureRecognizer *popBackInteractivePopGesture; // @synthesize popBackInteractivePopGesture=_popBackInteractivePopGesture;
@property(retain, nonatomic) UIScrollView *detaiInSideScrollView; // @synthesize detaiInSideScrollView=_detaiInSideScrollView;
@property(retain, nonatomic) UIPanGestureRecognizer *panGesture; // @synthesize panGesture=_panGesture;
@property(retain, nonatomic) MMUIButton *backgroundButton; // @synthesize backgroundButton=_backgroundButton;
@property(retain, nonatomic) MMUIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) MMUIView *topView; // @synthesize topView=_topView;
@property(retain, nonatomic) MMUIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(nonatomic) _Bool isHideBackgroupMask; // @synthesize isHideBackgroupMask=_isHideBackgroupMask;
@property(retain, nonatomic) UIView *detailView; // @synthesize detailView=_detailView;
@property(nonatomic) __weak id <MMUIHalfScreenViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long halfScreenViewControllerModel; // @synthesize halfScreenViewControllerModel=_halfScreenViewControllerModel;
@property(nonatomic) _Bool isHideSetupGradientEffect; // @synthesize isHideSetupGradientEffect=_isHideSetupGradientEffect;
- (void).cxx_destruct;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)doClickCloseWithNeedAnimated:(_Bool)arg1;
- (void)onClickClose;
- (void)scollerEndResetContentViewHeight:(double)arg1;
- (void)handleScrollViewPanGesture:(id)arg1;
- (void)handleTopViewPanGesture:(id)arg1;
- (id)interactionControllerForDismissal;
- (void)onDismissInteractiveTransitionBegin:(id)arg1;
- (void)addPopBackInteractivePopGesture;
@property(nonatomic) double halfScreenHeight; // @synthesize halfScreenHeight=_halfScreenHeight;
- (void)setUpScrollViewGradientLayer;
- (void)setUpScrollViewWithGradientEffect;
- (void)setupView;
- (void)viewDidLoad;
- (void)configPresentationCustomWithViewController:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

