//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "IExptServiceExt-Protocol.h"
#import "IMinimizeTaskDelegateInterface-Protocol.h"
#import "MMService-Protocol.h"

@class NSMutableDictionary, NSString;

@interface MPLandingPageMgr : MMService <IMinimizeTaskDelegateInterface, IExptServiceExt, MMService>
{
    _Bool _isOpenVideoNativePageExpt;
    NSMutableDictionary *_dicVideoPageUrl2Progress;
    NSMutableDictionary *_dictMinimizedPages;
}

+ (id)landingPageMinimizeDataFromTaskData:(id)arg1;
+ (void)updateTaskData:(id)arg1 pageObj:(id)arg2 minimizeType:(int)arg3;
+ (id)taskDataFromPageObj:(id)arg1 minimizeType:(int)arg2;
+ (id)genMinimizationMPLandingTaskKey;
+ (id)taskBizIdFromPageObj:(id)arg1;
+ (id)taskKeyFromPageObj:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *dictMinimizedPages; // @synthesize dictMinimizedPages=_dictMinimizedPages;
@property(retain, nonatomic) NSMutableDictionary *dicVideoPageUrl2Progress; // @synthesize dicVideoPageUrl2Progress=_dicVideoPageUrl2Progress;
@property(nonatomic) _Bool isOpenVideoNativePageExpt; // @synthesize isOpenVideoNativePageExpt=_isOpenVideoNativePageExpt;
- (void).cxx_destruct;
- (void)saveVideoProgress:(double)arg1 url:(id)arg2;
- (double)getVideoProgressByUrl:(id)arg1;
- (void)onExptItemListChange;
- (_Bool)isOpenVideoLandingPageSwitch;
- (void)onServiceReloadData;
- (void)onServiceInit;
- (void)dealloc;
- (void)onTaskEntryExposed:(id)arg1;
- (void)onLeaveTaskDoneAndWillEnterAnother:(id)arg1;
- (id)getLastViewControllerOnLeaveTaskBeforeEnterAnother:(id)arg1;
- (void)onRemoveTask:(id)arg1;
- (void)onEnterTask:(id)arg1 FromFloatingView:(id)arg2 EnterTaskScene:(int)arg3;
- (void)releaseMinimizeViewControler:(id)arg1;
- (void)unminimizeViewControler:(id)arg1;
- (void)minimizeLandingPageObj:(id)arg1 minimizeType:(int)arg2;
- (_Bool)canMinimizeLandingPaegObj:(id)arg1;
- (_Bool)isLandingPageHasMinimizedTask:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

