//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SolitaireConfigUtil : NSObject
{
}

+ (long long)getSolitaireBecomeActiveCount;
+ (long long)getSolitaireFirstMatchLimit;
+ (long long)getSolitaireMatchMaxCount;
+ (long long)getSolitaireMatchMaxDuration;
+ (long long)getSolitaireActiveMaxCount;
+ (long long)getSolitaireActiveMaxDuration;
+ (id)getSolitaireKeywordRegex;
+ (id)getSolitaireExampleRegex;
+ (id)getSolitaireContentRegex;
+ (long long)getSolitaireContentMaxCount;
+ (int)getSolitaireItemMaxWordCount;
+ (_Bool)isOpenKeywordDetection;
+ (_Bool)isSolitaireOpenAnalysis;
+ (_Bool)isSolitaireOpenEntry;

@end

