//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SolitaireReport.h"

@interface SolitaireActiveReport : SolitaireReport
{
    _Bool _bHasHeader;
    _Bool _bHasTail;
    _Bool _bHasExample;
    unsigned long long _activeScene;
}

@property(nonatomic) unsigned long long activeScene; // @synthesize activeScene=_activeScene;
@property(nonatomic) _Bool bHasExample; // @synthesize bHasExample=_bHasExample;
@property(nonatomic) _Bool bHasTail; // @synthesize bHasTail=_bHasTail;
@property(nonatomic) _Bool bHasHeader; // @synthesize bHasHeader=_bHasHeader;
- (void)report;

@end

