//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AVCaptureAudioDataOutputSampleBufferDelegate-Protocol.h"

@class AVAssetWriter, AVAssetWriterInput, AVAssetWriterInputPixelBufferAdaptor, NSString;

@interface VideoWriter : NSObject <AVCaptureAudioDataOutputSampleBufferDelegate>
{
    CDStruct_1b6d18a9 mStartTime;
    int mFps;
    int mWidth;
    int mHeight;
    unsigned int mDuration;
    unsigned int mGop;
    unsigned int mVideoWriteCnt;
    unsigned int mLogTick;
    long long mVideoFrameCnt;
    long long mLastFrameStamp;
    long long mLastKeyFrameStamp;
    long long mMaxFrameStamp;
    unsigned long long mLastCaptureStamp;
    _Bool _started;
    AVAssetWriter *_assetWriter;
    AVAssetWriterInput *_assetWriterVideoInput;
    AVAssetWriterInputPixelBufferAdaptor *_assetWriterInputPixelBufferAdaptor;
}

@property(nonatomic) _Bool started; // @synthesize started=_started;
@property(retain, nonatomic) AVAssetWriterInputPixelBufferAdaptor *assetWriterInputPixelBufferAdaptor; // @synthesize assetWriterInputPixelBufferAdaptor=_assetWriterInputPixelBufferAdaptor;
@property(retain, nonatomic) AVAssetWriterInput *assetWriterVideoInput; // @synthesize assetWriterVideoInput=_assetWriterVideoInput;
@property(retain, nonatomic) AVAssetWriter *assetWriter; // @synthesize assetWriter=_assetWriter;
- (void).cxx_destruct;
- (unsigned long long)getTickCount;
- (long long)getLastKeyFrameStamp;
- (void)stop:(CDUnknownBlockType)arg1;
- (void)abort;
- (void)resume;
- (void)pause;
- (void)writeVideo:(void *)arg1 size:(unsigned long long)arg2 width:(unsigned long long)arg3 height:(unsigned long long)arg4 bitsPerComponent:(unsigned long long)arg5 bytesPerRow:(unsigned long long)arg6 bitmapInfo:(unsigned int)arg7;
- (_Bool)start:(id)arg1 width:(int)arg2 height:(int)arg3 fps:(int)arg4 gop:(int)arg5 bitRate:(int)arg6 duration:(long long)arg7;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

