//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAWebViewPlugin_embedView.h"

#import "MMScreenRecorderDelegate-Protocol.h"
#import "WAOpenGlViewScreenCaptureDelegate-Protocol.h"

@class NSString;

@interface WAWebViewPlugin_ScreenRecorder : WAWebViewPlugin_embedView <WAOpenGlViewScreenCaptureDelegate, MMScreenRecorderDelegate>
{
    _Bool _isStarted;
    unsigned int _frameCnt;
}

@property(nonatomic) unsigned int frameCnt; // @synthesize frameCnt=_frameCnt;
@property(nonatomic) _Bool isStarted; // @synthesize isStarted=_isStarted;
- (void)sendEvent:(id)arg1 param:(id)arg2;
- (void)notifyTimeStampChange:(long long)arg1;
- (void)notifyError:(int)arg1 errMsg:(id)arg2;
- (void)notifyStop:(id)arg1 tempThumbPath:(id)arg2 duration:(unsigned int)arg3 fileSize:(unsigned int)arg4;
- (void)notifyAbort;
- (void)notifyResume;
- (void)notifyPause;
- (void)notifyStart;
- (id)getContact;
- (void)editResult:(id)arg1 result:(int)arg2 videoInfo:(id)arg3 callback:(CDUnknownBlockType)arg4;
- (id)audioCacheDataPathForSrc:(id)arg1 src:(id)arg2;
- (id)audioTmpPathByfileName:(id)arg1 fileName:(id)arg2;
- (id)audioTmpRootPath:(id)arg1;
- (id)localPathByAudioData:(id)arg1 data:(id)arg2 pathExtension:(id)arg3;
- (id)checkFilePath:(id)arg1 path:(id)arg2;
- (void)onScreenCapture:(void *)arg1 size:(unsigned long long)arg2 width:(unsigned long long)arg3 height:(unsigned long long)arg4 bitsPerComponent:(unsigned long long)arg5 bytesPerRow:(unsigned long long)arg6 bitmapInfo:(unsigned int)arg7;
- (_Bool)isScreenCaptureStart;
- (void)removeMediaTrack:(id)arg1 dic:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)updateMediaTrack:(id)arg1 dic:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)createMediaTrack:(id)arg1 dic:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)getMediaTrack:(id)arg1 dic:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)removeMediaContainer:(id)arg1 dic:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)exportMediaContainer:(id)arg1 dic:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)createMediaContainer:(id)arg1 dic:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)edit:(id)arg1 dic:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)abort:(id)arg1 dic:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)stop:(id)arg1 dic:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)resume:(id)arg1 dic:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)pause:(id)arg1 dic:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)start:(id)arg1 dic:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

