//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

@class NSString, OpenApiParameter, UIView;
@protocol WCShareAuthViewControllerDelegate;

@interface WCShareAuthViewController : MMUIViewController
{
    _Bool bIsFromSysCopy;
    int _type;
    unsigned int _msgType;
    id <WCShareAuthViewControllerDelegate> _delegate;
    NSString *_appName;
    NSString *_extText;
    NSString *_extUrl;
    NSString *_desc;
    NSString *_appBrandUserName;
    NSString *_appBrandPath;
    NSString *_userOpenId;
    NSString *_songAlbumUrl;
    UIView *_scrollView;
    UIView *_errView;
    NSString *_errString;
    OpenApiParameter *_openParam;
}

@property(retain, nonatomic) OpenApiParameter *openParam; // @synthesize openParam=_openParam;
@property(retain, nonatomic) NSString *errString; // @synthesize errString=_errString;
@property(retain, nonatomic) UIView *errView; // @synthesize errView=_errView;
@property(retain, nonatomic) UIView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) NSString *songAlbumUrl; // @synthesize songAlbumUrl=_songAlbumUrl;
@property(retain, nonatomic) NSString *userOpenId; // @synthesize userOpenId=_userOpenId;
@property(retain, nonatomic) NSString *appBrandPath; // @synthesize appBrandPath=_appBrandPath;
@property(retain, nonatomic) NSString *appBrandUserName; // @synthesize appBrandUserName=_appBrandUserName;
@property(nonatomic) unsigned int msgType; // @synthesize msgType=_msgType;
@property(nonatomic) int type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) NSString *extUrl; // @synthesize extUrl=_extUrl;
@property(retain, nonatomic) NSString *extText; // @synthesize extText=_extText;
@property(retain, nonatomic) NSString *appName; // @synthesize appName=_appName;
@property(nonatomic) __weak id <WCShareAuthViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool bIsFromSysCopy; // @synthesize bIsFromSysCopy;
- (void).cxx_destruct;
- (void)reportTranslateLinkFail:(id)arg1 result:(id)arg2;
- (void)checkIfNeedUpdateAppDataFromServer:(id)arg1 version:(unsigned int)arg2;
- (void)sendAuthRequest;
- (void)didNeedRedirectUrlWithResult:(id)arg1;
- (void)didNeedRefreshTokenWithResult:(id)arg1;
- (void)didFail;
- (void)didSuccessWithResult:(id)arg1;
- (void)goBack;
- (void)onBackBtnClick:(id)arg1;
- (id)getType;
- (id)makeLink;
- (id)navigationBarBackgroundColor;
- (void)viewDidLoad;
- (id)initWithType:(int)arg1 openParam:(id)arg2 txt:(id)arg3 url:(id)arg4 msgType:(unsigned int)arg5 desc:(id)arg6 songAlbumUrl:(id)arg7 extraData:(id)arg8;
- (id)initWithType:(int)arg1 openParam:(id)arg2 txt:(id)arg3 url:(id)arg4 msgType:(unsigned int)arg5 desc:(id)arg6 extraData:(id)arg7;
- (id)initWithType:(int)arg1 openParam:(id)arg2 txt:(id)arg3 url:(id)arg4 msgType:(unsigned int)arg5 songAlbumUrl:(id)arg6;
- (id)initWithType:(int)arg1 openParam:(id)arg2 txt:(id)arg3 url:(id)arg4 msgType:(unsigned int)arg5;
- (void)dealloc;

@end

