//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

@class MMWebSearchController;

@interface WSTemplateViewController : MMUIViewController
{
    MMWebSearchController *_webSearchController;
}

@property(retain, nonatomic) MMWebSearchController *webSearchController; // @synthesize webSearchController=_webSearchController;
- (void).cxx_destruct;
- (void)viewDidLoad;

@end

